export const dogBreeds = [
    'Labrador Retriever',
    'German Shepherd',
    'Golden Retriever',
    'French Bulldog',
    'Bulldog',
    'Poodle',
    'Beagle',
    'Rottweiler',
    'German Shorthaired Pointer',
    'Dachshund',
    'Pembroke Welsh Corgi',
    'Australian Shepherd',
    'Yorkshire Terrier',
    'Boxer',
    'Cavalier King Charles Spaniel',
    'Doberman Pinscher',
    'Great Dane',
    'Miniature Schnauzer',
    'Siberian Husky',
    'Bernese Mountain Dog',
    'Shih Tzu',
    'Boston Terrier',
    'Pomeranian',
    'Havanese',
    'English Springer Spaniel',
    'Mixed Breed'
];

export const catBreeds = [
    'Persian',
    'Maine Coon',
    'Siamese',
    'Ragdoll',
    'British Shorthair',
    'Abyssinian',
    'Scottish Fold',
    'Sphynx',
    'Bengal',
    'American Shorthair',
    'Birman',
    'Oriental Shorthair',
    'Devon Rex',
    'Norwegian Forest Cat',
    'Russian Blue',
    'Exotic Shorthair',
    'Burmese',
    'Tonkinese',
    'Savannah',
    'Manx',
    'Turkish Angora',
    'Himalayan',
    'Domestic Shorthair',
    'Mixed Breed'
];
